load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

py_binary(
    name = "embed_data",
    srcs = ["embed_data.py"],
)

py_binary(
    name = "embed_audio",
    srcs = ["embed_audio.py"],
)
