"""Compiles the game's music into the binary.

Every track under bgm/ is built into the executable, for the same reason the
textprotos are: the file a player runs is the whole game. The tracks are MP3
and go in whole -- miniaudio decodes them at play time.

They arrive as assembler `.incbin` directives rather than a C array, because
109 MB of audio is 109 million tokens for a compiler to parse and no work at
all for an assembler. The generated `.cc` is only the table naming them.
"""

import argparse
import os
import sys


def track_name(path):
    """The name a track is looked up by: its filename stem."""
    return os.path.splitext(os.path.basename(path))[0]


def write_asm(out, paths, include_dir):
    """Writes the .S that carries the audio itself.

    A .S (capital S) is preprocessed, which is what lets one file name the
    read-only section correctly for both ELF and the Windows cross-build.
    """
    out.write("/* Generated by tools/embed_audio.py. Do not edit. */\n")
    out.write("#if defined(_WIN32)\n")
    out.write('.section .rdata, "dr"\n')
    out.write("#else\n")
    out.write('.section .rodata\n')
    out.write("#endif\n\n")
    for i, path in enumerate(paths):
        out.write(".balign 16\n")
        out.write(".globl kBgm%d\n" % i)
        out.write("kBgm%d:\n" % i)
        out.write('.incbin "%s"\n' % os.path.join(include_dir, path))
        out.write(".globl kBgm%dEnd\n" % i)
        out.write("kBgm%dEnd:\n\n" % i)


def write_table(out, header_include, paths):
    """Writes the .cc naming each blob, sorted so lookup can bisect."""
    out.write("/* Generated by tools/embed_audio.py. Do not edit. */\n")
    out.write('#include "%s"\n\n' % header_include)
    out.write("#include <algorithm>\n#include <cstddef>\n")
    out.write("#include <iterator>\n#include <string_view>\n\n")
    out.write('extern "C" {\n')
    for i in range(len(paths)):
        out.write("extern const unsigned char kBgm%d[];\n" % i)
        out.write("extern const unsigned char kBgm%dEnd[];\n" % i)
    out.write("}\n\nnamespace ms {\nnamespace {\n\n")
    out.write("struct Entry {\n")
    out.write("  std::string_view name;\n")
    out.write("  const unsigned char* data;\n")
    out.write("  const unsigned char* end;\n")
    out.write("};\n\n")
    out.write("constexpr Entry kTracks[] = {\n")
    order = sorted(range(len(paths)), key=lambda i: track_name(paths[i]))
    for i in order:
        out.write('    {"%s", kBgm%d, kBgm%dEnd},\n'
                  % (track_name(paths[i]).replace('"', '\\"'), i, i))
    out.write("};\n\n}  // namespace\n\n")
    out.write("""std::optional<TrackData> BgmTrack(std::string_view track) {
  const Entry* it = std::lower_bound(
      std::begin(kTracks), std::end(kTracks), track,
      [](const Entry& e, std::string_view name) { return e.name < name; });
  if (it == std::end(kTracks) || it->name != track) {
    return std::nullopt;
  }
  return TrackData{it->data, static_cast<std::size_t>(it->end - it->data)};
}

std::vector<std::string_view> BgmTrackNames() {
  std::vector<std::string_view> names;
  names.reserve(std::size(kTracks));
  for (const Entry& entry : kTracks) {
    names.push_back(entry.name);
  }
  return names;
}

}  // namespace ms
""")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--asm", required=True)
    ap.add_argument("--table", required=True)
    ap.add_argument("--tracks", required=True,
                    help="comma-separated paths to the .mp3 files")
    args = ap.parse_args()

    paths = [p for p in args.tracks.split(",") if p]
    if not paths:
        sys.exit("embed_audio: no tracks. bgm/ is gitignored, so a fresh "
                 "clone has none; build with --define=audio=off for a build "
                 "without music.")
    names = [track_name(p) for p in paths]
    if len(set(names)) != len(names):
        sys.exit("embed_audio: two tracks share a name: %s"
                 % sorted({n for n in names if names.count(n) > 1}))

    with open(args.asm, "w") as out:
        write_asm(out, paths, "")
    with open(args.table, "w") as out:
        write_table(out, "src/audio/tracks.h", paths)


if __name__ == "__main__":
    main()
