"""Compiles the game's music into the binary.

Every track under bgm/ is built into the executable, for the same reason the
textprotos are: the file a player runs is the whole game. The tracks are MP3
and go in whole -- miniaudio decodes them at play time.

They arrive as assembler `.incbin` directives rather than a C array, because
109 MB of audio is 109 million tokens for a compiler to parse and no work at
all for an assembler. The generated `.cc` is only the table naming them.
"""

import argparse
import os
import sys

# MP3 Layer III bitrates in kbps, indexed by the header's four-bit field.
# MPEG-1 and MPEG-2/2.5 read different tables; index 15 is a reserved value.
_BITRATES = {
    1: [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 0],
    2: [0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144, 160, 0],
}
# Sample rates in Hz by MPEG version, indexed by the header's two-bit field.
_RATES = {1: [44100, 48000, 32000],
          2: [22050, 24000, 16000],
          25: [11025, 12000, 8000]}
_VERSIONS = {0: 25, 2: 2, 3: 1}


def track_name(path):
    """The name a track is looked up by: its filename stem."""
    return os.path.splitext(os.path.basename(path))[0]


def _id3_length(data):
    """Bytes of ID3v2 tag at the head of `data`, which carry no audio."""
    if data[:3] != b"ID3":
        return 0
    size = 0
    for byte in data[6:10]:
        size = (size << 7) | (byte & 0x7F)
    return 10 + size


def _frame(data, pos):
    """The frame starting at `pos` as (length, samples, rate), or None.

    None means `pos` is not a frame header, which is how the walk below
    resyncs past a tag or a run of padding.
    """
    if pos + 4 > len(data) or data[pos] != 0xFF or data[pos + 1] & 0xE0 != 0xE0:
        return None
    version = _VERSIONS.get(data[pos + 1] >> 3 & 3)
    # Layer III alone: it is what every track under bgm/ is.
    if version is None or data[pos + 1] >> 1 & 3 != 1:
        return None
    bitrate = _BITRATES[1 if version == 1 else 2][data[pos + 2] >> 4 & 0xF]
    rate_index = data[pos + 2] >> 2 & 3
    if bitrate == 0 or rate_index == 3:
        return None
    rate = _RATES[version][rate_index]
    samples = 1152 if version == 1 else 576
    padding = data[pos + 2] >> 1 & 1
    length = samples // 8 * bitrate * 1000 // rate + padding
    return (length, samples, rate) if length > 4 else None


def duration_ms(path):
    """How long `path` plays, by walking its frame headers.

    Exact for a variable bitrate as well as a constant one, and it decodes
    nothing: each header says how far the next one is. A file with no frames
    in it at all answers 0.
    """
    data = open(path, "rb").read()
    pos = _id3_length(data)
    samples = 0
    rate = 0
    while pos + 4 <= len(data):
        frame = _frame(data, pos)
        if frame is None:
            pos += 1
            continue
        length, frame_samples, rate = frame
        samples += frame_samples
        pos += length
    return samples * 1000 // rate if rate else 0


def write_asm(out, paths, include_dir):
    """Writes the .S that carries the audio itself.

    A .S (capital S) is preprocessed, which is what lets one file name the
    read-only section correctly for both ELF and the Windows cross-build.
    """
    out.write("/* Generated by tools/embed_audio.py. Do not edit. */\n")
    out.write("#if defined(_WIN32)\n")
    out.write('.section .rdata, "dr"\n')
    out.write("#else\n")
    out.write('.section .rodata\n')
    out.write("#endif\n\n")
    for i, path in enumerate(paths):
        out.write(".balign 16\n")
        out.write(".globl kBgm%d\n" % i)
        out.write("kBgm%d:\n" % i)
        out.write('.incbin "%s"\n' % os.path.join(include_dir, path))
        out.write(".globl kBgm%dEnd\n" % i)
        out.write("kBgm%dEnd:\n\n" % i)


def write_table(out, header_include, paths):
    """Writes the .cc naming each blob, sorted so lookup can bisect."""
    out.write("/* Generated by tools/embed_audio.py. Do not edit. */\n")
    out.write('#include "%s"\n\n' % header_include)
    out.write("#include <algorithm>\n#include <cstddef>\n")
    out.write("#include <iterator>\n#include <string_view>\n\n")
    out.write('extern "C" {\n')
    for i in range(len(paths)):
        out.write("extern const unsigned char kBgm%d[];\n" % i)
        out.write("extern const unsigned char kBgm%dEnd[];\n" % i)
    out.write("}\n\nnamespace ms {\nnamespace {\n\n")
    out.write("struct Entry {\n")
    out.write("  std::string_view name;\n")
    out.write("  const unsigned char* data;\n")
    out.write("  const unsigned char* end;\n")
    out.write("  int duration_ms;\n")
    out.write("};\n\n")
    out.write("constexpr Entry kTracks[] = {\n")
    order = sorted(range(len(paths)), key=lambda i: track_name(paths[i]))
    for i in order:
        out.write('    {"%s", kBgm%d, kBgm%dEnd, %d},\n'
                  % (track_name(paths[i]).replace('"', '\\"'), i, i,
                     duration_ms(paths[i])))
    out.write("};\n\n}  // namespace\n\n")
    out.write("""std::optional<TrackData> BgmTrack(std::string_view track) {
  const Entry* it = std::lower_bound(
      std::begin(kTracks), std::end(kTracks), track,
      [](const Entry& e, std::string_view name) { return e.name < name; });
  if (it == std::end(kTracks) || it->name != track) {
    return std::nullopt;
  }
  return TrackData{it->data, static_cast<std::size_t>(it->end - it->data),
                   it->duration_ms};
}

std::vector<std::string_view> BgmTrackNames() {
  std::vector<std::string_view> names;
  names.reserve(std::size(kTracks));
  for (const Entry& entry : kTracks) {
    names.push_back(entry.name);
  }
  return names;
}

}  // namespace ms
""")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--asm", required=True)
    ap.add_argument("--table", required=True)
    ap.add_argument("--tracks", required=True,
                    help="comma-separated paths to the .mp3 files")
    args = ap.parse_args()

    paths = [p for p in args.tracks.split(",") if p]
    if not paths:
        sys.exit("embed_audio: no tracks. bgm/ is gitignored, so a fresh "
                 "clone has none; build with --define=audio=off for a build "
                 "without music.")
    names = [track_name(p) for p in paths]
    if len(set(names)) != len(names):
        sys.exit("embed_audio: two tracks share a name: %s"
                 % sorted({n for n in names if names.count(n) > 1}))

    with open(args.asm, "w") as out:
        write_asm(out, paths, "")
    with open(args.table, "w") as out:
        write_table(out, "src/audio/tracks.h", paths)


if __name__ == "__main__":
    main()
