"""Compiles the game's textproto data files into a C++ table.

The shipped game has no data directory beside it: every .textproto under
data/ is built into the binary, so the executable on its own is the whole
game and there is no layout a player can break by moving it.

One group per data directory, each becoming one accessor returning a map
keyed by filename stem -- the same key LoadTextProtoDir gives a directory,
so the two are interchangeable to a caller.
"""

import argparse
import os
import sys


def escape(text):
    """Returns `text` as C string literal bodies, one per line of input.

    Non-ASCII bytes go out as three-digit octal rather than hex: a hex escape
    has no length limit, so a following hex digit would silently join it.
    """
    out = []
    for line in text.split("\n"):
        body = ""
        for byte in line.encode("utf-8"):
            char = chr(byte)
            if char == "\\":
                body += "\\\\"
            elif char == '"':
                body += '\\"'
            elif char == "\t":
                body += "\\t"
            elif 32 <= byte < 127:
                body += char
            else:
                body += "\\%03o" % byte
        out.append(body)
    return out


def read_group(paths):
    """Returns {stem: contents} for `paths`, refusing two files of one stem."""
    entries = {}
    for path in paths:
        stem = os.path.splitext(os.path.basename(path))[0]
        if stem in entries:
            sys.exit("Duplicate textproto name '%s' (%s)" % (stem, path))
        with open(path, encoding="utf-8") as handle:
            entries[stem] = handle.read()
    return entries


def write_header(path, include, symbols):
    guard = "MS_" + include.replace("/", "_").replace(".", "_").upper() + "_"
    lines = [
        "// Generated by tools/embed_data.py. Do not edit.",
        "#ifndef " + guard,
        "#define " + guard,
        "",
        "#include <map>",
        "#include <string>",
        "",
        "namespace ms {",
        "",
    ]
    for symbol in symbols:
        lines += [
            "// The data files of one directory, keyed by filename stem.",
            "const std::map<std::string, std::string>& %s();" % symbol,
            "",
        ]
    lines += ["}  // namespace ms", "", "#endif  // " + guard, ""]
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def write_source(path, include, groups):
    lines = [
        "// Generated by tools/embed_data.py. Do not edit.",
        '#include "%s"' % include,
        "",
        "#include <map>",
        "#include <string>",
        "",
        "namespace ms {",
        "namespace {",
        "",
    ]
    constants = {}
    index = 0
    for symbol in sorted(groups):
        for stem in sorted(groups[symbol]):
            name = "kFile%d" % index
            index += 1
            constants[(symbol, stem)] = name
            body = escape(groups[symbol][stem])
            lines.append("// %s/%s" % (symbol, stem))
            lines.append("const char %s[] =" % name)
            for i, chunk in enumerate(body):
                end = ";" if i == len(body) - 1 else ""
                lines.append('    "%s\\n"%s' % (chunk, end))
            lines.append("")
    lines += ["}  // namespace", ""]
    for symbol in sorted(groups):
        lines += [
            "const std::map<std::string, std::string>& %s() {" % symbol,
            "  // Leaked on purpose: the tables outlive every caller, and a",
            "  // static destructor would only run at exit.",
            "  static const std::map<std::string, std::string>* const kTable =",
            "      new std::map<std::string, std::string>{",
        ]
        for stem in sorted(groups[symbol]):
            lines.append('          {"%s", %s},' % (stem, constants[(symbol, stem)]))
        lines += ["      };", "  return *kTable;", "}", ""]
    lines += ["}  // namespace ms", ""]
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--header", required=True)
    parser.add_argument("--source", required=True)
    parser.add_argument("--header_include", required=True)
    parser.add_argument(
        "--group",
        action="append",
        default=[],
        metavar="SYMBOL=PATH,PATH",
        help="one accessor function and the files behind it",
    )
    args = parser.parse_args()

    groups = {}
    for spec in args.group:
        symbol, _, joined = spec.partition("=")
        paths = [path for path in joined.split(",") if path]
        groups[symbol] = read_group(paths)

    write_header(args.header, args.header_include, sorted(groups))
    write_source(args.source, args.header_include, groups)


if __name__ == "__main__":
    main()
