#!/usr/bin/env python3
"""Regenerates analysis/gms_mob_exp.cc from the MapleStory wiki.

The game's own mobs stop at level 60, so economy_sim has nothing to read
above that. This pulls GMS's real per-level mob EXP off the wiki's
"Monster/Level N - M" stat tables and writes it out as a C++ table, so the
sim itself stays hermetic and needs no network.

    python3 tools/fetch_gms_mob_exp.py

Fetched with plain curl; see tools/wikifetch.sh for what each wiki wants.
"""

import json
import re
import statistics
import subprocess
import sys
import time
import urllib.parse

API = "https://maplestorywiki.net/api.php"
MAX_LEVEL = 300
OUT = "analysis/gms_mob_exp.cc"

# Each stat table row is name / level / HP / MP / PDR / MDR / EXP.
ROW = re.compile(
    r"\|-[^\n]*\n\|(?:.*?)\n\|([\d,]+)\n\|([\d,]+)\n\|(?:[\d,]+)\n"
    r"\|(?:[^\n]*)\n\|(?:[^\n]*)\n\|([\d,]+)"
)


def fetch(title):
    url = "%s?%s" % (API, urllib.parse.urlencode({
        "action": "query", "prop": "revisions", "rvprop": "content",
        "rvslots": "main", "titles": title, "format": "json",
        "formatversion": "2"}))
    out = subprocess.run(["curl", "-s", url], capture_output=True, text=True)
    page = json.loads(out.stdout)["query"]["pages"][0]
    if "revisions" not in page:
        raise SystemExit("no such page: %s" % title)
    return page["revisions"][0]["slots"]["main"]["content"]


def scrape():
    """Every mob on the wiki as (level, hp, exp)."""
    mobs = []
    for lo in range(1, MAX_LEVEL, 10):
        text = fetch("Monster/Level %d - %d" % (lo, lo + 9))
        for level, hp, exp in ROW.findall(text):
            n = lambda s: int(s.replace(",", ""))
            mobs.append((n(level), n(hp), n(exp)))
        time.sleep(0.2)
    if len(mobs) < 1000:
        raise SystemExit("only %d mobs parsed -- the table markup moved" %
                         len(mobs))
    return mobs


def field_mobs(at_level):
    """The grindable mobs at one level.

    Drops bosses, which carry HP far above the level's norm, and party-quest
    filler, which carries EXP far below it. Either one left in would drag the
    level's EXP an order of magnitude off.
    """
    if not at_level:
        return []
    hp_mid = statistics.median(hp for _, hp, _ in at_level)
    kept = [m for m in at_level if m[1] <= 5 * hp_mid]
    if not kept:
        return []
    exp_mid = statistics.median(exp for _, _, exp in kept)
    return [m for m in kept if m[2] >= exp_mid / 10.0]


def curve(mobs):
    """EXP per kill at each level, as a player training level-appropriately.

    The upper quartile of the level's field mobs, because a player picks the
    best map open to them rather than the average one. That choice is what
    calibrates this against the engine: it holds the curve within a few
    percent of what //analysis:level_sim earns over the range the game can
    actually be played across.
    """
    by_level = {}
    for level, hp, exp in mobs:
        if exp > 0:
            by_level.setdefault(level, []).append((level, hp, exp))

    raw = {}
    for level in range(1, MAX_LEVEL):
        found = field_mobs(by_level.get(level, []))
        if found:
            exps = sorted(exp for _, _, exp in found)
            raw[level] = exps[min(len(exps) - 1, int(0.75 * len(exps)))]

    # Read each level through a +/-4 window: it fills the dozen levels the
    # wiki has no ordinary mob for, and stops one thin level from swinging it.
    out = []
    for level in range(1, MAX_LEVEL):
        near = [raw[x] for x in range(level - 4, level + 5) if x in raw]
        if not near:
            near = [raw[min(raw, key=lambda x: abs(x - level))]]
        out.append(statistics.median(near))

    # EXP per kill never falls as mobs get harder; a dip is thin data, not GMS.
    best = 0.0
    for i, value in enumerate(out):
        best = out[i] = max(best, value)
    return out


def emit(values):
    lines = ["""// GENERATED by tools/fetch_gms_mob_exp.py -- do not edit by hand.
//
// EXP one kill of a level-appropriate GMS field mob yields, by level, read off
// the MapleStory wiki's "Monster/Level N - M" stat tables. The game's own mobs
// stop at 60; this is what economy_sim reads above that.
#include "analysis/gms_mob_exp.h"

namespace ms {
namespace {

const double kExpPerKill[] = {"""]
    row = []
    for i, value in enumerate(values):
        row.append("%.0f," % value)
        if len(row) == 8:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("""};

}  // namespace

double GmsMobExpPerKill(int level) {
  if (level < 1 || level > static_cast<int>(sizeof(kExpPerKill) /
                                            sizeof(kExpPerKill[0]))) {
    return 0.0;
  }
  return kExpPerKill[level - 1];
}

}  // namespace ms""")
    return "\n".join(lines) + "\n"


def main():
    mobs = scrape()
    values = curve(mobs)
    # The levels the game has its own mobs for are the only check available:
    # Stump is 35 EXP at 20 and Wooden Mask 233 at 60 in data/mobs, and the
    # scrape has to land near those or it is reading the wrong column. Only
    # levels with enough mobs to quartile are worth checking -- at level 1 the
    # upper quartile is a Spore, not the Snail.
    for level, expected in ((20, 35), (60, 239)):
        got = values[level - 1]
        if abs(got - expected) > 0.15 * expected:
            raise SystemExit("level %d reads %.0f EXP, expected about %d -- "
                             "the column order moved" % (level, got, expected))
    open(OUT, "w").write(emit(values))
    # Leave the tree formatted, or the next run of the project formatter shows
    # up as a diff nobody made.
    subprocess.run(["clang-format", "-i", OUT], check=True)
    print("wrote %s from %d mobs" % (OUT, len(mobs)))


if __name__ == "__main__":
    sys.exit(main())
